#AFTER CLEAR SCREEB

'''    / / / (_)___ _/ /_  ___  _____
  / /_/ / / __ `/ __ \/ _ \/ ___/
 / __  / / /_/ / / / /  __/ /    
/_/ ///_/\__, /_/ /_/\___/_/     
   / /  /____/_      _____  _____
  / /   / __ \ | /| / / _ \/ ___/
 / /___/ /_/ / |/ |/ /  __/ /    
/_____/\____/|__/|__/\___/_/     

you are right! Current Score: 1
Compare A:NBA , a Club Basketball Competition , from United States

 _    __    
| |  / /____
| | / / ___/
| |/ (__  ) 
|___/____(_)

Against B:Kylie Jenner , a Reality TV personality and businesswoman and Self-Made Billionaire , from United States
Who has more followers ?Type 'A' or 'B' : '''