'''Do You want to play a game of Blackjack? Type 'y' or 'n':   y

.------.            _     _            _    _            _    
|A_  _ |.          | |   | |          | |  (_)          | |   
|( \/ ).-----.     | |__ | | __ _  ___| | ___  __ _  ___| | __
| \  /|K /\  |     | '_ \| |/ _` |/ __| |/ / |/ _` |/ __| |/ /
|  \/ | /  \ |     | |_) | | (_| | (__|   <| | (_| | (__|   < 
`-----| \  / |     |_.__/|_|\__,_|\___|_|\_\ |\__,_|\___|_|\_\
      |  \/ K|                            _/ |
      `------'                           |__/

     Your cards: [8, 5] , current score:13
     Computer's first cards: 11 
Type 'y' to get another card , type 'n' to pass: y
     Your cards: [8, 5, 7] , current score:20
     Computer's first cards: 11 
Type 'y' to get another card , type 'n' to pass: n
 Your Final hand : [8, 5, 7] ,final score: 20
 Computer 's Final hand : [11, 4, 4] ,final score: 19
You win! 😃 Your score is higher.
Do You want to play a game of Blackjack? Type 'y' or 'n':   y

.------.            _     _            _    _            _
|A_  _ |.          | |   | |          | |  (_)          | |
|( \/ ).-----.     | |__ | | __ _  ___| | ___  __ _  ___| | __
| \  /|K /\  |     | '_ \| |/ _` |/ __| |/ / |/ _` |/ __| |/ /
|  \/ | /  \ |     | |_) | | (_| | (__|   <| | (_| | (__|   <
`-----| \  / |     |_.__/|_|\__,_|\___|_|\_\ |\__,_|\___|_|\_\
      |  \/ K|                            _/ |
      `------'                           |__/

     Your cards: [5, 7] , current score:12
     Computer's first cards: 4
Type 'y' to get another card , type 'n' to pass: y
     Your cards: [5, 7, 8] , current score:20
     Computer's first cards: 4
Type 'y' to get another card , type 'n' to pass: n
 Your Final hand : [5, 7, 8] ,final score: 20
 Computer 's Final hand : [4, 11, 2] ,final score: 17
You win! 😃 Your score is higher.
Do You want to play a game of Blackjack? Type 'y' or 'n':   y

.------.            _     _            _    _            _
|A_  _ |.          | |   | |          | |  (_)          | |
|( \/ ).-----.     | |__ | | __ _  ___| | ___  __ _  ___| | __
| \  /|K /\  |     | '_ \| |/ _` |/ __| |/ / |/ _` |/ __| |/ /
|  \/ | /  \ |     | |_) | | (_| | (__|   <| | (_| | (__|   <
`-----| \  / |     |_.__/|_|\__,_|\___|_|\_\ |\__,_|\___|_|\_\
      |  \/ K|                            _/ |
      `------'                           |__/

     Your cards: [10, 10] , current score:20
     Computer's first cards: 10
Type 'y' to get another card , type 'n' to pass: n
 Your Final hand : [10, 10] ,final score: 20
 Computer 's Final hand : [10, 3, 3, 10] ,final score: 26
You win! 😃 Computer went over 21.
Do You want to play a game of Blackjack? Type 'y' or 'n':   y

.------.            _     _            _    _            _
|A_  _ |.          | |   | |          | |  (_)          | |
|( \/ ).-----.     | |__ | | __ _  ___| | ___  __ _  ___| | __
| \  /|K /\  |     | '_ \| |/ _` |/ __| |/ / |/ _` |/ __| |/ /
|  \/ | /  \ |     | |_) | | (_| | (__|   <| | (_| | (__|   <
`-----| \  / |     |_.__/|_|\__,_|\___|_|\_\ |\__,_|\___|_|\_\
      |  \/ K|                            _/ |
      `------'                           |__/

     Your cards: [10, 6] , current score:16
     Computer's first cards: 10
Type 'y' to get another card , type 'n' to pass: y
     Your cards: [10, 6, 2] , current score:18
     Computer's first cards: 10
Type 'y' to get another card , type 'n' to pass: n
 Your Final hand : [10, 6, 2] ,final score: 18
 Computer 's Final hand : [10, 3, 5] ,final score: 18
Draw'''