#genrate random number 1 to 100
from random import randint





print("Welcome to the Number Guessing Game! ")
print("I m thinking if a number between 1 and 100. ")
answer=randint(1,100)


    
# make function to choose difficulty easy or hard

#let user gues a number
guess=int(input("Make a guess: "))
#a function to check user's guess against actual answer

#track the number of turns and reduce by 1 if they get wrong

#reapeating the guessing functionality if theey get wrong
