''' 
  / _ \_   _  ___  ___ ___  /__   \ |__   ___    /\ \ \_   _ _ __ ___ | |__   ___ _ __
 / /_\/ | | |/ _ \/ __/ __|   / /\/ '_ \ / _ \  /  \/ / | | | '_ ` _ \| '_ \ / _ \ '__|
/ /_\| |_| |  __/\__ \__ \  / /  | | | |  __/ / /\  /| |_| | | | | | | |_) |  __/ |
\____/ \__,_|\___||___/___/  \/   |_| |_|\___| \_\ \/  \__,_|_| |_| |_|_.__/ \___|_|

Welcome to the Number Guessing Game!
I m thinking if a number between 1 and 100.
Choose a difficulty . Type 'Easy' or 'Hard' Hard
you have 5 attempts remaining to guess the number.
Make a guess: 34
Too high
Guess Again
you have 4 attempts remaining to guess the number.
Make a guess: 23
Too high
Guess Again
you have 3 attempts remaining to guess the number.
Make a guess: 13
Too high
Guess Again
you have 2 attempts remaining to guess the number.
Make a guess: 8
you got it. your answer was 8

'''

'''   / _ \_   _  ___  ___ ___  /__   \ |__   ___    /\ \ \_   _ _ __ ___ | |__   ___ _ __ 
 / /_\/ | | |/ _ \/ __/ __|   / /\/ '_ \ / _ \  /  \/ / | | | '_ ` _ \| '_ \ / _ \ '__|
/ /_\| |_| |  __/\__ \__ \  / /  | | | |  __/ / /\  /| |_| | | | | | | |_) |  __/ |   
\____/ \__,_|\___||___/___/  \/   |_| |_|\___| \_\ \/  \__,_|_| |_| |_|_.__/ \___|_|  

Welcome to the Number Guessing Game! 
I m thinking if a number between 1 and 100. 
Choose a difficulty . Type 'Easy' or 'Hard' Easy
you have 10 attempts remaining to guess the number.
Make a guess: 23
Too low
Guess Again
you have 9 attempts remaining to guess the number.
Make a guess: 33
Too low
Guess Again
you have 8 attempts remaining to guess the number.
Make a guess: 45
Too low
Guess Again
you have 7 attempts remaining to guess the number.
Make a guess: 67
you got it. your answer was 67 '''


'''  / _ \_   _  ___  ___ ___  /__   \ |__   ___    /\ \ \_   _ _ __ ___ | |__   ___ _ __ 
 / /_\/ | | |/ _ \/ __/ __|   / /\/ '_ \ / _ \  /  \/ / | | | '_ ` _ \| '_ \ / _ \ '__|
/ /_\| |_| |  __/\__ \__ \  / /  | | | |  __/ / /\  /| |_| | | | | | | |_) |  __/ |   
\____/ \__,_|\___||___/___/  \/   |_| |_|\___| \_\ \/  \__,_|_| |_| |_|_.__/ \___|_|  

Welcome to the Number Guessing Game! 
I m thinking if a number between 1 and 100. 
Choose a difficulty . Type 'Easy' or 'Hard' Hard
you have 5 attempts remaining to guess the number.
Make a guess: 45
Too high
Guess Again
you have 4 attempts remaining to guess the number.
Make a guess: 56
Too high
Guess Again
you have 3 attempts remaining to guess the number.
Make a guess: 78
Too high
Guess Again
you have 2 attempts remaining to guess the number.
Make a guess: 78
Too high
Guess Again
you have 1 attempts remaining to guess the number.
Make a guess: 89
Too high
you have run out of guesses , you lose.'''